[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'

# 括弧補完
[[plugins]]
repo = 'cohama/lexima.vim'

# リントツール
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/nvim/plugins/anzu.vim
'''

# 日本語ドキュメント
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# syntax for toml
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'ziglang/zig.vim'
