os:
  copyToClipboardCmd: 'echo -n "{{text}}" | osc copy'
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  language: en
  nerdFontsVersion: 3
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: true
  log:
    showWholeGraph: true
  parseEmoji: true
  branchLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(#a0a0a0 reverse)%h%Creset %C(cyan)%ad%Creset %C(#dd4814)%ae%Creset %C(yellow reverse)%d%Creset %n%C(white bold)%s%Creset%n' {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --color=always --date=format:'%Y-%m-%d %H:%M' --pretty=format:'%C(#a0a0a0 reverse)%h%Creset %C(cyan)%ad%Creset %C(#dd4814)%ae%Creset %C(yellow reverse)%d%Creset %n%C(white bold)%s%Creset%n' --
